<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.ros.org/schema/package_format3.xsd"?>
<package format="3">
  <name>ms02_mobile_robot_control</name>
  <version>1.0.0</version>
  <description>Go-To-Pose controller node for ROS 2 Turtlesim (Milestone 02 / Project 1)</description>
  <maintainer email="hashir@todo.todo">Hashir Ali</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>geometry_msgs</depend>
  <depend>turtlesim</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
